-- MySQL Script generated by MySQL Workbench
-- Wed Jul  2 12:01:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema devsubd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `devsubd` ;

-- -----------------------------------------------------
-- Schema devsubd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `devsubd` DEFAULT CHARACTER SET utf8 ;
USE `devsubd` ;

-- -----------------------------------------------------
-- Table `devsubd`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devsubd`.`Persona` ;

CREATE TABLE IF NOT EXISTS `devsubd`.`Persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC) VISIBLE
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `devsubd`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devsubd`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `devsubd`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_persona_idx` (`persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_persona`
    FOREIGN KEY (`persona_id`) REFERENCES `devsubd`.`Persona` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devsubd`.`cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devsubd`.`cuenta` ;

CREATE TABLE IF NOT EXISTS `devsubd`.`Cuenta` (
    `numero_cuenta` VARCHAR(45) NOT NULL,
    `tipo_cuenta` VARCHAR(45) NOT NULL,
    `saldo_inicial` DECIMAL(15,2) NOT NULL,
    `estado` TINYINT(1) NOT NULL,
    `cliente_id` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`numero_cuenta`)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devsubd`.`Movimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devsubd`.`Movimiento` ;

CREATE TABLE IF NOT EXISTS `devsubd`.`Movimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `tipo_movimiento` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(15,2) NOT NULL,
  `saldo` DECIMAL(15,2) NOT NULL,
  `numero_cuenta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movimiento_cuenta_idx` (`numero_cuenta` ASC) VISIBLE,
  CONSTRAINT `fk_movimiento_cuenta`
    FOREIGN KEY (`numero_cuenta`) REFERENCES `devsubd`.`Cuenta` (`numero_cuenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
